Add New Phones
wonderlandpark/phonepare pull request #15
Opened 2021-03-24 06:17 UTC by UniqueDevStorm

Apple
- iPhone 12 Pro Max
- iPhone 12 Pro
- iPhone 12
- iPhone 12 mini
Samsung
- Z Filp
- Fold
- Fold 2
- Galaxy S20 FE
- Galaxy S21
- Galaxy S21+
- Galaxy Note20
- Galaxy Note20 Ultra

또한 새로운 색상이 추가되면서 색상 28가지 추가했습니다.
getPhone.js 부분도 아주 살짝 return 부분 변경했습니다.

2021-03-28 14:54 UTC, wonderlandpark commented
Thx for the PR.

I will review it soon

2021-04-12 04:44 UTC, wonderlandpark requested changes
Looks Good 👀

2021-04-12 04:44 UTC, wonderlandpark commented on src/getPhone.js
> +        image: {src: `/phones/${el.id}.jpg`}
Better looking
```suggestion
        image: { src: `/phones/${el.id}.jpg` }
```

2021-04-12 04:44 UTC, wonderlandpark commented on src/phone.json
> +      "id": "zfilp",
typo
```suggestion
      "id": "zflip",
```

2021-04-12 04:47 UTC, UniqueDevStorm commented on src/phone.json
> +      "id": "zfilp",
> typo

Oops, There was typo

2021-04-12 05:25 UTC, wonderlandpark commented on src/getPhone.js
> +        image: {src: `/phones/${el.id}.jpg`}
Why are you resolving this?

2021-04-12 05:25 UTC, wonderlandpark commented on src/phone.json
> +      "id": "zfilp",
Why are you resolving this?

2021-04-15 02:09 UTC, wonderlandpark commented
@UniqueDevStorm Could you commit my suggestion? I could merge it right now.

2021-04-15 02:46 UTC, wonderlandpark requested changes
Looks like Note 20 5G and zFlip 5G is missing image 😢

2021-04-15 02:52 UTC, UniqueDevStorm commented
> Looks like Note 20 5G and zFlip 5G is missing image 😢

The name has been changed, but the image value seems to have not changed.

2021-04-15 03:18 UTC, wonderlandpark commented
<img width="416" alt="image" src="https://user-images.githubusercontent.com/31924512/114809162-a5851a00-9de4-11eb-9308-b42e654b2c82.png">
Could you double-check it? Looks like it's not fixed yet.

2021-04-15 04:04 UTC, UniqueDevStorm commented
https://phonepare-1.vercel.app
I'm done fixing it.

2021-04-15 04:04 UTC, wonderlandpark approved these changes

2021-04-15 04:04 UTC, merged

2021-04-15 04:04 UTC, wonderlandpark commented
Thanks for your contribution

2021-04-15 04:11 UTC, UniqueDevStorm commented
> Thanks for your contribution

I will update you when another smartphone comes out next time.