added some smartphones
wonderlandpark/phonepare pull request #35
Opened 2021-09-29 10:19 UTC by UniqueDevStorm

## added a few colors
- midnight
- starlight
- blue
- apple pink

## added some smartphones
- iPhone 13 mini
- iPhone 13
- iPhone 13 Pro
- iPhone 13 Pro Max
- Galaxy Fold 5G 3
- Galaxy Z Flip3 5G

2021-10-12 10:40 UTC, wonderlandpark requested changes

2021-10-12 10:40 UTC, wonderlandpark commented on .gitignore
> +.idea
Please do not change code not related to PR

2021-10-12 10:40 UTC, wonderlandpark commented on src/lib/question.ts
> +        label: '전 게임은 많이 플레이하지 않습니다.',
This too

2021-10-12 10:41 UTC, wonderlandpark requested changes
There is no color named `퍼시픽 플루` at iPhone 13 Pro (Max) model. I must be `시에라 블루`

2021-10-12 10:53 UTC, ZeroOneDeveloper commented
I'm so sorry, I updated what you said, and I also updated the battery capacity that I wrote incorrectly.

2021-10-14 09:06 UTC, wonderlandpark approved these changes

2021-10-14 09:06 UTC, merged